services:
  app:
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      discocat:
        aliases:
          - pearson-pulse

networks:
  discocat:
    external: true
    name: discocat_internal
